export type StandardAccountTemplate = {
  code: string;
  name: string;
  accountType: 'asset' | 'liability' | 'equity' | 'cost' | 'expense' | 'revenue';
  normalBalance: 'debit' | 'credit';
  isLeaf?: boolean;
  isCash?: boolean;
  isBank?: boolean;
  allowManualEntry?: boolean;
  category: string;
};

export const standardAccountTemplates: StandardAccountTemplate[] = [
  { code: '1001', name: '库存现金', accountType: 'asset', normalBalance: 'debit', isCash: true, category: '资产类' },
  { code: '1002', name: '银行存款', accountType: 'asset', normalBalance: 'debit', isBank: true, category: '资产类' },
  { code: '1012', name: '其他货币资金', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1101', name: '短期投资', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1121', name: '应收票据', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1122', name: '应收账款', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1123', name: '预付账款', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1131', name: '应收股利', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1132', name: '应收利息', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1221', name: '其他应收款', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1401', name: '材料采购', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1402', name: '在途物资', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1403', name: '原材料', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1404', name: '材料成本差异', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1405', name: '库存商品', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1407', name: '商品进销差价', accountType: 'asset', normalBalance: 'credit', category: '资产类' },
  { code: '1408', name: '委托加工物资', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1411', name: '周转材料', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1421', name: '消耗性生物资产', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1501', name: '长期债券投资', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1511', name: '长期股权投资', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1601', name: '固定资产', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1602', name: '累计折旧', accountType: 'asset', normalBalance: 'credit', category: '资产类' },
  { code: '1604', name: '在建工程', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1605', name: '工程物资', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1606', name: '固定资产清理', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1621', name: '生产性生物资产', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1622', name: '生产性生物资产累计折旧', accountType: 'asset', normalBalance: 'credit', category: '资产类' },
  { code: '1701', name: '无形资产', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1702', name: '累计摊销', accountType: 'asset', normalBalance: 'credit', category: '资产类' },
  { code: '1801', name: '长期待摊费用', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '1901', name: '待处理财产损溢', accountType: 'asset', normalBalance: 'debit', category: '资产类' },
  { code: '2001', name: '短期借款', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2201', name: '应付票据', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2202', name: '应付账款', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2203', name: '预收账款', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2211', name: '应付职工薪酬', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2221', name: '应交税费', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2231', name: '应付利息', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2232', name: '应付利润', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2241', name: '其他应付款', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2401', name: '递延收益', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2501', name: '长期借款', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '2701', name: '长期应付款', accountType: 'liability', normalBalance: 'credit', category: '负债类' },
  { code: '3001', name: '实收资本', accountType: 'equity', normalBalance: 'credit', category: '所有者权益类' },
  { code: '3002', name: '资本公积', accountType: 'equity', normalBalance: 'credit', category: '所有者权益类' },
  { code: '3101', name: '盈余公积', accountType: 'equity', normalBalance: 'credit', category: '所有者权益类' },
  { code: '3103', name: '本年利润', accountType: 'equity', normalBalance: 'credit', category: '所有者权益类' },
  { code: '3104', name: '利润分配', accountType: 'equity', normalBalance: 'credit', category: '所有者权益类' },
  { code: '4001', name: '生产成本', accountType: 'cost', normalBalance: 'debit', category: '成本类' },
  { code: '4101', name: '制造费用', accountType: 'cost', normalBalance: 'debit', category: '成本类' },
  { code: '4301', name: '研发支出', accountType: 'cost', normalBalance: 'debit', category: '成本类' },
  { code: '4401', name: '工程施工', accountType: 'cost', normalBalance: 'debit', category: '成本类' },
  { code: '4403', name: '机械作业', accountType: 'cost', normalBalance: 'debit', category: '成本类' },
  { code: '5001', name: '主营业务收入', accountType: 'revenue', normalBalance: 'credit', category: '损益类' },
  { code: '5051', name: '其他业务收入', accountType: 'revenue', normalBalance: 'credit', category: '损益类' },
  { code: '5111', name: '投资收益', accountType: 'revenue', normalBalance: 'credit', category: '损益类' },
  { code: '5301', name: '营业外收入', accountType: 'revenue', normalBalance: 'credit', category: '损益类' },
  { code: '5401', name: '主营业务成本', accountType: 'expense', normalBalance: 'debit', category: '损益类' },
  { code: '5402', name: '其他业务成本', accountType: 'expense', normalBalance: 'debit', category: '损益类' },
  { code: '5403', name: '税金及附加', accountType: 'expense', normalBalance: 'debit', category: '损益类' },
  { code: '5601', name: '销售费用', accountType: 'expense', normalBalance: 'debit', category: '损益类' },
  { code: '5602', name: '管理费用', accountType: 'expense', normalBalance: 'debit', category: '损益类' },
  { code: '5603', name: '财务费用', accountType: 'expense', normalBalance: 'debit', category: '损益类' },
  { code: '5711', name: '营业外支出', accountType: 'expense', normalBalance: 'debit', category: '损益类' },
  { code: '5801', name: '所得税费用', accountType: 'expense', normalBalance: 'debit', category: '损益类' },
];
